package reporter

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/ayb-blc/solsec/internal/analyzer"
)

// solsec scan . --format markdown > AUDIT_REPORT.md
type MarkdownReporter struct {
	out         io.Writer
	projectName string
}

func NewMarkdown(out io.Writer, projectName string) *MarkdownReporter {
	return &MarkdownReporter{out: out, projectName: projectName}
}

func (r *MarkdownReporter) Report(results []analyzer.AnalysisResult) error {
	stats := ComputeStats(results)
	w := r.out

	fmt.Fprintf(w, "# Security Audit Report: %s\n\n", r.projectName)
	fmt.Fprintf(w, "> Generated by **solsec** on %s  \n",
		time.Now().Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintf(w, "> %d files analyzed · %d findings\n\n",
		stats.TotalFiles, stats.TotalFindings)

	if stats.TotalFindings == 0 {
		fmt.Fprintf(w, "## ✅ No vulnerabilities detected\n\n")
		fmt.Fprintf(w, "All %d analyzed files passed security checks.\n", stats.TotalFiles)
		return nil
	}

	// Executive Summary tablosu
	r.writeExecutiveSummary(w, stats)

	grouped := groupBySeverity(results)

	for _, sev := range []analyzer.Severity{
		analyzer.Critical, analyzer.High, analyzer.Medium, analyzer.Low, analyzer.Info,
	} {
		findings, ok := grouped[sev]
		if !ok || len(findings) == 0 {
			continue
		}
		r.writeSeveritySection(w, sev, findings)
	}

	r.writeDetectorAppendix(w, results)

	return nil
}

func (r *MarkdownReporter) writeExecutiveSummary(w io.Writer, stats SummaryStats) {
	fmt.Fprintf(w, "## Executive Summary\n\n")
	fmt.Fprintf(w, "| Severity | Count | Risk |\n")
	fmt.Fprintf(w, "|----------|-------|------|\n")

	for _, sev := range []analyzer.Severity{
		analyzer.Critical, analyzer.High, analyzer.Medium, analyzer.Low, analyzer.Info,
	} {
		count := stats.BySeverity[sev]
		if count == 0 {
			continue
		}
		icon := markdownSeverityIcon(sev)
		risk := severityRiskDescription(sev)
		fmt.Fprintf(w, "| %s %s | **%d** | %s |\n", icon, sev, count, risk)
	}
	fmt.Fprintf(w, "\n")
}

// writeSeveritySection writes one severity group as a Markdown section.
func (r *MarkdownReporter) writeSeveritySection(
	w io.Writer,
	sev analyzer.Severity,
	findings []findingWithFile,
) {
	icon := markdownSeverityIcon(sev)
	fmt.Fprintf(w, "## %s %s Findings (%d)\n\n", icon, sev, len(findings))

	for i, fw := range findings {
		f := fw.finding

		fmt.Fprintf(w, "### [%s-%d] %s\n\n", sev.String()[:1], i+1, f.Title)

		// Metadata tablosu
		fmt.Fprintf(w, "| Field | Value |\n|-------|-------|\n")
		fmt.Fprintf(w, "| **Detector** | `%s` |\n", f.DetectorName)
		fmt.Fprintf(w, "| **Severity** | %s %s |\n", icon, sev)
		fmt.Fprintf(w, "| **Confidence** | %s |\n", f.Confidence)

		if f.Filepath != "" {
			location := f.Filepath
			if f.Line > 0 {
				location = fmt.Sprintf("%s (line %d)", f.Filepath, f.Line)
			}
			fmt.Fprintf(w, "| **Location** | `%s` |\n", location)
		}

		if len(f.Tags) > 0 {
			tags := make([]string, len(f.Tags))
			for j, t := range f.Tags {
				tags[j] = "`" + t + "`"
			}
			fmt.Fprintf(w, "| **Tags** | %s |\n", strings.Join(tags, ", "))
		}
		fmt.Fprintf(w, "\n")

		if f.CodeSnippet != "" {
			fmt.Fprintf(w, "**Vulnerable Code:**\n\n")
			fmt.Fprintf(w, "```solidity\n%s\n```\n\n", f.CodeSnippet)
		}

		if f.Description != "" {
			fmt.Fprintf(w, "**Description:**\n\n%s\n\n", f.Description)
		}

		if f.Recommendation != "" {
			fmt.Fprintf(w, "**Recommendation:**\n\n%s\n\n", f.Recommendation)
		}

		fmt.Fprintf(w, "---\n\n")
	}
}

func (r *MarkdownReporter) writeDetectorAppendix(w io.Writer, results []analyzer.AnalysisResult) {
	fmt.Fprintf(w, "## Appendix: Detector Reference\n\n")
	fmt.Fprintf(w, "| Detector | Description |\n|----------|-------------|\n")

	seen := make(map[string]bool)
	for _, result := range results {
		for _, f := range result.Findings {
			if !seen[f.DetectorName] {
				seen[f.DetectorName] = true
				fmt.Fprintf(w, "| `%s` | %s |\n",
					f.DetectorName,
					truncate(f.Description, 80),
				)
			}
		}
	}
	fmt.Fprintf(w, "\n")
}

func markdownSeverityIcon(sev analyzer.Severity) string {
	switch sev {
	case analyzer.Critical:
		return "🔴"
	case analyzer.High:
		return "🟠"
	case analyzer.Medium:
		return "🟡"
	case analyzer.Low:
		return "🔵"
	default:
		return "⚪"
	}
}

func severityRiskDescription(sev analyzer.Severity) string {
	switch sev {
	case analyzer.Critical:
		return "Direct fund loss or contract takeover"
	case analyzer.High:
		return "Significant security impact, likely exploitable"
	case analyzer.Medium:
		return "Moderate risk, requires specific conditions"
	case analyzer.Low:
		return "Best practice violation, low exploit potential"
	default:
		return "Informational"
	}
}
