package formal

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/ayb-blc/solsec/internal/analyzer"
)

// EchidnaRunner bridges solsec findings to Echidna fuzzing runs.
type EchidnaRunner struct {
	binaryPath string
	timeout    time.Duration
	corpusDir  string
}

func NewEchidnaRunner(binaryPath string, timeout time.Duration) *EchidnaRunner {
	if binaryPath == "" {
		binaryPath = "echidna"
	}
	if timeout == 0 {
		timeout = 5 * time.Minute
	}
	return &EchidnaRunner{
		binaryPath: binaryPath,
		timeout:    timeout,
	}
}

func (r *EchidnaRunner) Tool() Tool { return ToolEchidna }

func (r *EchidnaRunner) IsAvailable() ToolAvailability {
	out, err := exec.Command(r.binaryPath, "--version").Output()
	if err != nil {
		return ToolAvailability{Tool: ToolEchidna, Available: false, Error: err.Error()}
	}
	return ToolAvailability{
		Tool:      ToolEchidna,
		Available: true,
		Version:   strings.TrimSpace(string(out)),
		Path:      r.binaryPath,
	}
}

func (r *EchidnaRunner) Run(target *FuzzTarget) (*VerificationResult, error) {
	result := &VerificationResult{
		Tool:   ToolEchidna,
		Target: target,
	}

	testFile, cleanup, err := r.prepareTestFile(target)
	if err != nil {
		result.Status = StatusError
		result.Error = err.Error()
		return result, nil
	}
	defer cleanup()

	configFile, configCleanup, err := r.writeConfig(target)
	if err != nil {
		result.Status = StatusError
		result.Error = err.Error()
		return result, nil
	}
	defer configCleanup()

	start := time.Now()
	output, err := r.runEchidna(testFile, configFile, target.ContractName)
	result.Duration = time.Since(start)

	if err != nil {
		if !isViolationExitCode(err) {
			result.Status = StatusError
			result.Error = err.Error()
			result.RawOutput = string(output)
			return result, nil
		}
	}

	result.RawOutput = string(output)

	violations := r.parseOutput(output)
	if len(violations) > 0 {
		result.Status = StatusViolation
		result.Violations = violations
	} else {
		result.Status = StatusSafe
	}

	return result, nil
}

func (r *EchidnaRunner) prepareTestFile(target *FuzzTarget) (string, func(), error) {
	original, err := os.ReadFile(target.ContractPath)
	if err != nil {
		return "", nil, fmt.Errorf("read contract: %w", err)
	}

	var sb strings.Builder
	sb.Write(original)
	sb.WriteString("\n\n// === Echidna Properties (generated by solsec) ===\n")
	sb.WriteString(fmt.Sprintf("// Source finding: %s\n", target.SourceFinding.Title))
	sb.WriteString(fmt.Sprintf("// Severity: %s\n\n", target.SourceFinding.Severity))

	sb.WriteString(fmt.Sprintf("contract %s_EchidnaTest is %s {\n",
		target.ContractName, target.ContractName))

	sb.WriteString("    // Test setup\n")
	sb.WriteString("    address internal echidna_caller = msg.sender;\n")
	sb.WriteString("    bool internal _reentrancyDetected = false;\n\n")

	for _, prop := range target.Properties {
		sb.WriteString(fmt.Sprintf("    // Property: %s\n", prop.Name))
		sb.WriteString(fmt.Sprintf("    // %s\n", prop.Description))
		sb.WriteString(prop.SolidityCode)
		sb.WriteString("\n\n")
	}

	sb.WriteString("}\n")

	dir := filepath.Dir(target.ContractPath)
	f, err := os.CreateTemp(dir, "echidna_test_*.sol")
	if err != nil {
		return "", nil, err
	}
	f.WriteString(sb.String())
	f.Close()

	return f.Name(), func() { os.Remove(f.Name()) }, nil
}

func (r *EchidnaRunner) writeConfig(target *FuzzTarget) (string, func(), error) {
	config := map[string]interface{}{
		"testMode":    "property",
		"testLimit":   50000,
		"timeout":     int(r.timeout.Seconds()),
		"shrinkLimit": 5000,
		"quiet":       false,
		"format":      "json",
	}

	if len(target.SeedValues) > 0 {
		seeds := make([]interface{}, len(target.SeedValues))
		for i, sv := range target.SeedValues {
			seeds[i] = map[string]string{
				"name":  sv.ParamName,
				"value": sv.Value,
			}
		}
		config["seeds"] = seeds
	}

	// Corpus dizini
	if r.corpusDir != "" {
		corpusPath := filepath.Join(r.corpusDir, target.ContractName)
		os.MkdirAll(corpusPath, 0o755)
		config["corpusDir"] = corpusPath
	}

	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return "", nil, err
	}

	f, err := os.CreateTemp("", "echidna_config_*.yaml")
	if err != nil {
		return "", nil, err
	}
	f.Write(data)
	f.Close()

	return f.Name(), func() { os.Remove(f.Name()) }, nil
}

func (r *EchidnaRunner) runEchidna(
	testFile, configFile, contractName string,
) ([]byte, error) {
	args := []string{
		testFile,
		"--contract", contractName + "_EchidnaTest",
		"--config", configFile,
		"--format", "json",
	}

	ctx, cancel := timeoutContext(r.timeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, r.binaryPath, args...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	output := stdout.Bytes()
	if len(output) == 0 {
		output = stderr.Bytes()
	}
	return output, err
}

func (r *EchidnaRunner) parseOutput(output []byte) []Violation {
	var violations []Violation

	for _, line := range bytes.Split(output, []byte("\n")) {
		line = bytes.TrimSpace(line)
		if len(line) == 0 {
			continue
		}

		var event map[string]interface{}
		if err := json.Unmarshal(line, &event); err != nil {
			continue
		}

		eventType, _ := event["event"].(string)
		if eventType != "PropertyFailed" && eventType != "TestFailed" {
			continue
		}

		name, _ := event["name"].(string)
		violations = append(violations, Violation{
			PropertyName:   name,
			Description:    fmt.Sprintf("Echidna falsified property: %s", name),
			CounterExample: r.extractCounterExample(event),
			Severity:       analyzer.Critical,
		})
	}

	return violations
}

func (r *EchidnaRunner) extractCounterExample(event map[string]interface{}) *CounterExample {
	ce := &CounterExample{}

	if calls, ok := event["calls"].([]interface{}); ok {
		for _, call := range calls {
			if callMap, ok := call.(map[string]interface{}); ok {
				cc := ContractCall{
					Function: fmt.Sprintf("%v", callMap["function"]),
					Caller:   fmt.Sprintf("%v", callMap["caller"]),
					Value:    fmt.Sprintf("%v", callMap["value"]),
				}
				if args, ok := callMap["args"].([]interface{}); ok {
					for _, arg := range args {
						cc.Args = append(cc.Args, fmt.Sprintf("%v", arg))
					}
				}
				ce.Calls = append(ce.Calls, cc)
			}
		}
	}

	return ce
}

func isViolationExitCode(err error) bool {
	if exitErr, ok := err.(*exec.ExitError); ok {
		return exitErr.ExitCode() == 1
	}
	return false
}
