package formal

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/ayb-blc/solsec/internal/analyzer"
)

// ManticoreRunner bridges solsec findings to Manticore symbolic execution runs.
type ManticoreRunner struct {
	binaryPath string
	timeout    time.Duration
	outputDir  string
}

func NewManticoreRunner(binaryPath string, timeout time.Duration) *ManticoreRunner {
	if binaryPath == "" {
		binaryPath = "manticore"
	}
	if timeout == 0 {
		timeout = 10 * time.Minute
	}
	return &ManticoreRunner{
		binaryPath: binaryPath,
		timeout:    timeout,
	}
}

func (r *ManticoreRunner) Tool() Tool { return ToolManticore }

func (r *ManticoreRunner) IsAvailable() ToolAvailability {
	out, err := exec.Command(r.binaryPath, "--version").Output()
	if err != nil {
		// Python module olarak dene
		out2, err2 := exec.Command("python3", "-m", "manticore", "--version").Output()
		if err2 != nil {
			return ToolAvailability{
				Tool:      ToolManticore,
				Available: false,
				Error:     err.Error(),
			}
		}
		return ToolAvailability{
			Tool:      ToolManticore,
			Available: true,
			Version:   strings.TrimSpace(string(out2)),
			Path:      "python3 -m manticore",
		}
	}
	return ToolAvailability{
		Tool:      ToolManticore,
		Available: true,
		Version:   strings.TrimSpace(string(out)),
		Path:      r.binaryPath,
	}
}

func (r *ManticoreRunner) Run(target *FuzzTarget) (*VerificationResult, error) {
	result := &VerificationResult{
		Tool:   ToolManticore,
		Target: target,
	}

	scriptFile, cleanup, err := r.preparePythonScript(target)
	if err != nil {
		result.Status = StatusError
		result.Error = err.Error()
		return result, nil
	}
	defer cleanup()

	start := time.Now()
	output, err := r.runManticore(scriptFile)
	result.Duration = time.Since(start)
	result.RawOutput = string(output)

	if err != nil {
		if strings.Contains(err.Error(), "killed") ||
			strings.Contains(string(output), "timeout") {
			result.Status = StatusTimeout
			return result, nil
		}
		result.Status = StatusError
		result.Error = err.Error()
		return result, nil
	}

	violations := r.parseOutput(output, target)
	if len(violations) > 0 {
		result.Status = StatusViolation
		result.Violations = violations
	} else {
		result.Status = StatusSafe
	}

	// Coverage bilgisini al
	result.Coverage = r.parseCoverage(output)

	return result, nil
}

func (r *ManticoreRunner) preparePythonScript(target *FuzzTarget) (string, func(), error) {
	var sb strings.Builder

	sb.WriteString("#!/usr/bin/env python3\n")
	sb.WriteString("# Manticore analysis script — generated by solsec\n")
	sb.WriteString(fmt.Sprintf("# Source finding: %s\n", target.SourceFinding.Title))
	sb.WriteString(fmt.Sprintf("# Contract: %s.%s\n\n", target.ContractName, target.FunctionName))

	sb.WriteString(fmt.Sprintf(`
import sys
import json
from manticore.ethereum import ManticoreEVM
from manticore.core.smtlib import operators

# Setup
m = ManticoreEVM()
m.verbosity(0)

# Load contract
with open(%q) as f:
    source = f.read()

owner = m.make_account(balance=10**18, name="owner")
attacker = m.make_account(balance=10**18, name="attacker")

try:
    contract = m.solidity_create_contract(source, owner=owner,
                                           contract_name=%q)
except Exception as e:
    print(f"Contract creation failed: {e}", file=sys.stderr)
    sys.exit(1)

violations = []

`, target.ContractPath, target.ContractName))

	for _, prop := range target.Properties {
		if prop.PythonCode != "" {
			sb.WriteString(fmt.Sprintf("# Property: %s\n", prop.Name))
			sb.WriteString(prop.PythonCode)
			sb.WriteString("\n")
		} else {
			// Genel symbolic execution
			sb.WriteString(fmt.Sprintf(`
# Generic symbolic test for: %s
try:
    amount = m.make_symbolic_value(name="amount_%s")
    m.transaction(
        caller=attacker,
        address=contract,
        value=0,
        data=ABI.function_call("%s", amount) if "%s" else b"",
    )
except Exception as e:
    print(f"Transaction failed: {e}", file=sys.stderr)

`, prop.Name, prop.Name, target.FunctionName, target.FunctionName))
		}
	}

	sb.WriteString(`
# Collect results
results = {
    "violations": violations,
    "states": {
        "ready": m.count_ready_states(),
        "killed": m.count_killed_states(),
        "finished": m.count_finished_states(),
    }
}

print(json.dumps(results))
m.finalize()
`)

	if len(target.SeedValues) > 0 {
		sb.WriteString("\n# Seed values for reference:\n")
		for _, sv := range target.SeedValues {
			sb.WriteString(fmt.Sprintf("# %s = %s (%s)\n",
				sv.ParamName, sv.Value, sv.Reason))
		}
	}

	f, err := os.CreateTemp("", "manticore_script_*.py")
	if err != nil {
		return "", nil, err
	}
	f.WriteString(sb.String())
	f.Close()

	return f.Name(), func() { os.Remove(f.Name()) }, nil
}

func (r *ManticoreRunner) runManticore(scriptFile string) ([]byte, error) {
	ctx, cancel := timeoutContext(r.timeout)
	defer cancel()

	outDir, _ := os.MkdirTemp("", "manticore_out_*")
	defer os.RemoveAll(outDir)

	cmd := exec.CommandContext(ctx, "python3", scriptFile)
	cmd.Env = append(os.Environ(),
		"MANTICORE_WORKSPACE="+outDir,
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	output := stdout.Bytes()
	if len(output) == 0 {
		output = stderr.Bytes()
	}
	return output, err
}

func (r *ManticoreRunner) parseOutput(output []byte, target *FuzzTarget) []Violation {
	var violations []Violation

	lines := bytes.Split(output, []byte("\n"))
	for _, line := range lines {
		line = bytes.TrimSpace(line)
		if !bytes.HasPrefix(line, []byte("{")) {
			continue
		}

		var result map[string]interface{}
		if err := json.Unmarshal(line, &result); err != nil {
			continue
		}

		if vs, ok := result["violations"].([]interface{}); ok {
			for _, v := range vs {
				if vm, ok := v.(map[string]interface{}); ok {
					violations = append(violations, Violation{
						PropertyName: fmt.Sprintf("%v", vm["property"]),
						Description:  fmt.Sprintf("%v", vm["description"]),
						Severity:     analyzer.Critical,
					})
				}
			}
		}
	}

	for _, pattern := range []string{
		"REENTRANCY FOUND",
		"ARITHMETIC VIOLATION",
		"ACCESS CONTROL VIOLATION",
		"VIOLATION",
	} {
		if bytes.Contains(bytes.ToUpper(output), []byte(pattern)) {
			violations = append(violations, Violation{
				PropertyName: pattern,
				Description: fmt.Sprintf(
					"Manticore detected: %s in %s.%s",
					pattern, target.ContractName, target.FunctionName,
				),
				Severity: analyzer.Critical,
			})
		}
	}

	return violations
}

func (r *ManticoreRunner) parseCoverage(output []byte) *CoverageInfo {
	lines := bytes.Split(output, []byte("\n"))
	for _, line := range lines {
		line = bytes.TrimSpace(line)
		if !bytes.HasPrefix(line, []byte("{")) {
			continue
		}
		var data map[string]interface{}
		if err := json.Unmarshal(line, &data); err != nil {
			continue
		}
		if states, ok := data["states"].(map[string]interface{}); ok {
			ready := int(toFloat(states["ready"]))
			finished := int(toFloat(states["finished"]))
			total := ready + finished + int(toFloat(states["killed"]))
			if total > 0 {
				return &CoverageInfo{
					LinesCovered: finished,
					LinesTotal:   total,
				}
			}
		}
	}
	return nil
}

func toFloat(v interface{}) float64 {
	if f, ok := v.(float64); ok {
		return f
	}
	return 0
}

// WriteAnalysisScript writes a generated Manticore analysis script to disk.
func (r *ManticoreRunner) WriteAnalysisScript(
	target *FuzzTarget,
	outputPath string,
) error {
	scriptFile, cleanup, err := r.preparePythonScript(target)
	if err != nil {
		return err
	}
	defer cleanup()

	content, err := os.ReadFile(scriptFile)
	if err != nil {
		return err
	}

	return os.WriteFile(outputPath, content, 0o644)
}

func GenerateManticoreScript(target *FuzzTarget, outputDir string) error {
	runner := NewManticoreRunner("", 0)
	scriptPath := filepath.Join(outputDir,
		fmt.Sprintf("manticore_%s_%s.py",
			target.ContractName, target.FunctionName))
	return runner.WriteAnalysisScript(target, scriptPath)
}
